site_name: PingCAP Docs
site_description: PingCAP documentation with Markdown.
site_author: PingCAP I18N Team

theme:
  name: 'material'

nav:
  - 关于 TiDB:
    - TiDB 简介: overview.md 
    - TiDB 整体架构: architecture.md 
    - TiDB 核心特性: features.md 
  - TiDB 快速入门:
    - 快速入门指南: QUICKSTART.md 
    - SQL 基本操作: try-tidb.md 
  - TiDB 用户文档:
    - TiDB 数据库管理:
        - TiDB 服务: sql/tidb-server.md 
        - TiDB 进程启动参数: sql/server-command-option.md 
        - TiDB 数据目录: sql/tidb-server.md#tidb-数据目录 
        - TiDB 系统数据库: sql/system-database.md 
        - TiDB 系统变量: sql/variable.md 
        - TiDB 专用系统变量和语法: sql/tidb-specific.md 
        - TiDB 服务器日志文件: sql/tidb-server.md#tidb-服务器日志文件 
        - TiDB 访问权限管理: sql/privilege.md 
        - TiDB 用户账户管理: sql/user-account-management.md 
        - 使用加密连接: sql/encrypted-connections.md 
    - TiDB SQL 优化和执行:
        - SQL 优化流程简介: sql/sql-optimizer-overview.md 
        - 理解 TiDB 执行计划: sql/understanding-the-query-execution-plan.md 
        - 统计信息: sql/statistics.md 
    - 语言结构:
        - 字面值: sql/literal-values.md 
        - 数据库、表、索引、列和别名: sql/schema-object-names.md 
        - 关键字和保留字: sql/keywords-and-reserved-words.md 
        - 用户变量: sql/user-defined-variables.md 
        - 表达式语法: sql/expression-syntax.md 
        - 注释语法: sql/comment-syntax.md 
    - 字符集和时区:
        - 字符集支持: sql/character-set-support.md 
        - 字符集配置: sql/character-set-configuration.md 
        - 时区: sql/time-zone.md 
    - 数据类型:
        - 数值类型: sql/datatype.md#数值类型 
        - 日期和时间类型: sql/date-and-time-types.md 
        - 字符串类型: sql/datatype.md#字符串类型 
        - JSON 数据类型: sql/datatype.md#json-类型 
        - 枚举类型: sql/datatype.md#枚举类型 
        - 集合类型: sql/datatype.md#集合类型 
        - 数据类型默认值: sql/datatype.md#数据类型的默认值 
    - 函数和操作符:
        - 函数和操作符概述: sql/functions-and-operators-reference.md 
        - 表达式求值的类型转换: sql/type-conversion-in-expression-evaluation.md 
        - 操作符: sql/operators.md 
        - 控制流程函数: sql/control-flow-functions.md 
        - 字符串函数: sql/string-functions.md 
        - 数值函数与操作符: sql/numeric-functions-and-operators.md 
        - 日期和时间函数: sql/date-and-time-functions.md 
        - 位函数和操作符: sql/bit-functions-and-operators.md 
        - Cast 函数和操作符: sql/cast-functions-and-operators.md 
        - 加密和压缩函数: sql/encryption-and-compression-functions.md 
        - 信息函数: sql/information-functions.md 
        - JSON 函数: sql/json-functions.md 
        - GROUP BY 聚合函数: sql/aggregate-group-by-functions.md 
        - 其他函数: sql/miscellaneous-functions.md 
        - 精度数学: sql/precision-math.md 
    - SQL 语句语法:
        - 数据定义语句  DDL : sql/ddl.md 
        - 数据操作语句  DML : sql/dml.md 
        - 事务语句: sql/transaction.md 
        - 数据库管理语句: sql/admin.md 
        - Prepared SQL 语句语法: sql/prepare.md 
        - 实用工具语句: sql/util.md 
        - TiDB SQL 语法图: https://pingcap.github.io/sqlgram/ 
        - Generated Column: sql/generated-columns.md 
        - Connectors 和 API: sql/connection-and-APIs.md 
        - TiDB 事务隔离级别: sql/transaction-isolation.md 
        - 错误码与故障诊断: sql/error.md 
        - 与 MySQL 兼容性对比: sql/mysql-compatibility.md 
        - TiDB 内存控制: sql/tidb-memory-control.md 
        - 慢查询日志: sql/slow-query.md 
    - 高级功能:
        - 历史数据回溯: op-guide/history-read.md 
        - 垃圾回收  GC : op-guide/gc.md 
  - TiDB 运维文档:
    - 软硬件环境需求: op-guide/recommendation.md 
    - 部署集群:
      - Ansible 部署方案（强烈推荐）: op-guide/ansible-deployment.md 
      - 离线 Ansible 部署方案: op-guide/offline-ansible-deployment.md 
      - Docker 部署方案: op-guide/docker-deployment.md 
      - Docker Compose 部署方案: op-guide/docker-compose.md 
      - 跨数据中心部署方案: op-guide/cross-dc-deployment.md 
    - 配置集群:
      - 参数解释: op-guide/configuration.md 
      - TiDB 配置项解释: op-guide/tidb-config-file.md 
      - 使用 Ansible 变更组件配置: op-guide/ansible-deployment-rolling-update.md#变更组件配置 
      - 开启 TLS 验证: op-guide/security.md 
      - 生成自签名证书: op-guide/generate-self-signed-certificates.md 
      - 集群拓扑结构配置: op-guide/location-awareness.md 
    - 监控集群:
      - 整体监控框架概述: op-guide/monitor-overview.md 
      - 重要监控指标详解:
        - Overview: op-guide/dashboard-overview-info.md 
        - TiDB: op-guide/tidb-dashboard-info.md 
        - PD: op-guide/dashboard-pd-info.md 
        - TiKV: op-guide/dashboard-tikv-info.md 
        - 组件状态 API & 监控: op-guide/monitor.md 
      - 扩容缩容:
        - 集群扩容缩容方案: op-guide/horizontal-scale.md 
        - 使用 Ansible 扩容缩容: op-guide/ansible-deployment-scale.md 
      - 升级:
        - 升级组件版本: op-guide/ansible-deployment-rolling-update.md#升级组件版本 
        - TiDB 2.0 升级操作指南: op-guide/tidb-v2.0-upgrade-guide.md 
        - TiDB 2.1 升级操作指南: op-guide/tidb-v2.1-upgrade-guide.md 
      - 性能调优: op-guide/tune-tikv.md 
      - 备份与迁移:
        - 备份与恢复: op-guide/backup-restore.md 
        - 数据迁移:
            - 数据迁移概述: op-guide/migration-overview.md 
            - 全量导入: op-guide/migration.md#使用-mydumperloader-全量导入数据 
            - 增量导入: op-guide/migration.md#使用-syncer-增量导入数据 
  - 故障诊断: trouble-shooting.md 
  - TiDB 周边工具:
    - Syncer: tools/syncer.md 
    - mydumper: tools/mydumper.md 
    - Loader: tools/loader.md 
    - TiDB-Lightning:
        - 简介: tools/lightning/overview-architecture.md 
        - 部署执行: tools/lightning/deployment.md 
        - 断点续传: tools/lightning/checkpoints.md 
        - 表库过滤: tools/lightning/filter.md 
        - 监控告警: tools/lightning/monitor.md 
        - 故障诊断: tools/lightning/errors.md 
        - 常见问题与解答: tools/lightning/faq.md 
    - TiDB-Binlog: tools/tidb-binlog-cluster.md 
    - PD Control: tools/pd-control.md 
    - PD Recover: tools/pd-recover.md 
    - TiKV Control: tools/tikv-control.md 
    - TiDB Controller: tools/tidb-controller.md 
    - 工具下载: tools/download.md 
  - TiSpark 文档:
    - TiSpark 快速入门指南: tispark/tispark-quick-start-guide.md 
    - TiSpark 用户指南: tispark/tispark-user-guide.md 
  - 常见问题与解答 FAQ : FAQ.md
  - 最佳实践: https://pingcap.com/blog-cn/tidb-best-practice/ 

markdown_extensions:
    - admonition
    - def_list